### ISSUE TITLE
yarn test fails to build

### ISSUE THREAD

**Issue by bradh** [ngageoint/opensphere-plugin-example#6]
```
> opensphere-plugin-example@1.0.0 test:gcc /home/bradh/opensphere-yarn-workspace/workspace/opensphere-plugin-example
> os-compile $(cat .build/gcc-test-args)

/home/bradh/opensphere-yarn-workspace/node_modules/google-closure-library/closure/goog/base.js:2122: WARNING - Parse error. unknown @suppress parameter: strictMissingProperties
 * @suppress {strictMissingProperties} superClass_ and base is not defined on
              ^



/home/bradh/opensphere-yarn-workspace/node_modules/google-closure-library/closure/goog/date/date.js:17: WARNING - Parse error. unknown @suppress parameter: checkPrototypalTypes
 * @suppress {checkPrototypalTypes}
              ^


/home/bradh/opensphere-yarn-workspace/node_modules/google-closure-library/closure/goog/db/keyrange.js:59: WARNING - Parse error. unknown @suppress parameter: strictMissingProperties
 * @suppress {strictMissingProperties} Part of the go/strict_warnings_migration
              ^

/home/bradh/opensphere-yarn-workspace/node_modules/google-closure-library/closure/goog/db/keyrange.js:75: WARNING - Parse error. unknown @suppress parameter: strictMissingProperties
 * @suppress {strictMissingProperties} Part of the go/strict_warnings_migration
              ^

/home/bradh/opensphere-yarn-workspace/node_modules/google-closure-library/closure/goog/db/keyrange.js:90: WARNING - Parse error. unknown @suppress parameter: strictMissingProperties
 * @suppress {strictMissingProperties} Part of the go/strict_warnings_migration
              ^

/home/bradh/opensphere-yarn-workspace/node_modules/google-closure-library/closure/goog/db/keyrange.js:104: WARNING - Parse error. unknown @suppress parameter: strictMissingProperties
 * @suppress {strictMissingProperties} Part of the go/strict_warnings_migration
              ^


/home/bradh/opensphere-yarn-workspace/node_modules/google-closure-library/closure/goog/debug/debug.js:45: WARNING - Parse error. unknown @suppress parameter: strictMissingProperties
 * @suppress {strictMissingProperties} onerror is not defined as a property
              ^

/home/bradh/opensphere-yarn-workspace/node_modules/google-closure-library/closure/goog/debug/debug.js:245: WARNING - Parse error. unknown @suppress parameter: strictMissingProperties
 * @suppress {strictMissingProperties} properties not defined on err
              ^


/home/bradh/opensphere-yarn-workspace/node_modules/google-closure-library/closure/goog/dom/asserts.js:350: WARNING - Parse error. unknown @suppress parameter: strictMissingProperties
 * @suppress {strictMissingProperties} ownerDocument not defined on Object
              ^


/home/bradh/opensphere-yarn-workspace/node_modules/google-closure-library/closure/goog/dom/dom.js:24: WARNING - Parse error. unknown @suppress parameter: strictMissingProperties
 * @suppress {strictMissingProperties}
              ^



/home/bradh/opensphere-yarn-workspace/node_modules/google-closure-library/closure/goog/events/mousewheelhandler.js:136: WARNING - Parse error. unknown @suppress parameter: strictMissingProperties
 * @suppress {strictMissingProperties} Part of the go/strict_warnings_migration
              ^



/home/bradh/opensphere-yarn-workspace/node_modules/google-closure-library/closure/goog/i18n/datetimeformat.js:404: WARNING - Parse error. unknown @suppress parameter: strictMissingProperties
 * @suppress {strictMissingProperties} Part of the go/strict_warnings_migration
              ^



/home/bradh/opensphere-yarn-workspace/node_modules/google-closure-library/closure/goog/net/jsloader.js:337: WARNING - Parse error. unknown @suppress parameter: strictMissingProperties
 * @suppress {strictMissingProperties} Part of the go/strict_warnings_migration
              ^



/home/bradh/opensphere-yarn-workspace/node_modules/google-closure-library/closure/goog/structs/structs.js:23: WARNING - Parse error. unknown @suppress parameter: strictMissingProperties
 * @suppress {strictMissingProperties}
              ^



/home/bradh/opensphere-yarn-workspace/node_modules/google-closure-library/closure/goog/window/window.js:127: WARNING - Parse error. unknown @suppress parameter: strictMissingProperties
  /** @suppress {strictMissingProperties} */
                 ^



/home/bradh/opensphere-yarn-workspace/node_modules/google-closure-library/closure/goog/goog.js:86: ERROR - incorrect use of goog.base: May only be called directly.
export const base = goog.base;
                    ^^^^^^^^^



1 error(s), 15 warning(s)
```

Possibly needs update to reflect https://github.com/ngageoint/opensphere/commit/f4469dacc5c838abb0998d462a29f883a33a389b

**Comment by wallw-dev** [comment]
I believe this should have been fixed when #5 was merged. Can you pull and try again?

**Comment by bradh** [comment]
Its still throwing the same errors after a full clean checkout.

The steps (from bash history):
```
 1925  git clone git://github.com/ngageoint/opensphere-yarn-workspace 
 1926  cd opensphere-yarn-workspace/workspace/
 1927  git clone git://github.com/ngageoint/opensphere
 1928  git clone git://github.com/ngageoint/opensphere-plugin-example
 1929  cd ..
 1930  yarn install
 1931  cd workspace/opensphere
 1932  yarn build
 1933  cd ../opensphere-plugin-example/
 1934  yarn test
```

**Comment by bradh** [comment]
No longer seeing this problem.
